### ISSUE TITLE
Uncaught LogicException: byID can't be called on an UnsavedRelationList.

### ISSUE THREAD

**Issue by petrklus** [webbuilders-group/silverstripe-frontendgridfield#10]
I am experiencing issue using the front-end grid field:

```
        $gridFieldConfig = FrontEndGridFieldConfig_RelationEditor::create();        
        $gDayVis = new FrontEndGridField("DayToDayExtraDocuments", "Additional documents", $this->DayToDayExtraDocuments(), $gridFieldConfig);          
        $fields->push($gDayVis);   
```

I can see the fields in the front end and I am able to upload a file. The error presents itself after I press the "Create" button.

Details of the error:

```
[User Error] Uncaught LogicException: byID can't be called on an UnsavedRelationList.
GET /FrontEndInterface_controller/TravelPackTabForm/field/DayToDayExtraDocuments/item/5
Line 307 in /Users/petr/Google Drive/work/CNKSolutions repositories/rsc1-website/rsc1-with-composer/framework/model/UnsavedRelationList.php
Source
298     public function avg() {
299         throw new LogicException(__FUNCTION__ . " can't be called on an UnsavedRelationList.");
300     }
301 
302     public function byIDs() {
303         throw new LogicException(__FUNCTION__ . " can't be called on an UnsavedRelationList.");
304     }
305 
306     public function byID($id) {
307         throw new LogicException(__FUNCTION__ . " can't be called on an UnsavedRelationList.");
308     }
309 
310     public function dataQuery() {
311         throw new LogicException(__FUNCTION__ . " can't be called on an UnsavedRelationList.");
312     }
313 
Trace
UnsavedRelationList->byID(5) 
GridFieldDetailForm.php:86
GridFieldDetailForm->handleItem(FrontEndGridField,SS_HTTPRequest) 
GridField.php:716
GridField->handleRequest(SS_HTTPRequest,DataModel) 
RequestHandler.php:222
RequestHandler->handleRequest(SS_HTTPRequest,DataModel) 
RequestHandler.php:222
RequestHandler->handleRequest(SS_HTTPRequest,DataModel) 
Controller.php:153
Controller->handleRequest(SS_HTTPRequest,DataModel) 
ContentController.php:198
ContentController->handleRequest(SS_HTTPRequest,DataModel) 
Director.php:370
Director::handleRequest(SS_HTTPRequest,Session,DataModel) 
Director.php:153
Director::direct(/FrontEndInterface_controller/TravelPackTabForm/field/DayToDayExtraDocuments/item/5,DataModel)
main.php:177
```

**Comment by UndefinedOffset** [comment]
Ah UnsavedRelationList, it's a fun beast. Basically what you are experiencing is a deficiency in the core of SilverStripe 3.x. I'm guessing you are just creating the parent object (the one the FrontEndGridField lives in)? When a parent in the relationship is not yet saved for the first time SilverStripe 3.x uses UnsavedRelationList to represent it which isn't really that great, as you can see it's very limited in what it can actually do. The best workaround though not great, is to simply force the user to save the parent first before allowing them to interact with the GridField. Not ideal but I haven't found a good work around.

Personally I've tried many workarounds for UnsavedRelationList and don't have a solid solution for one that works. I.e [webbuilders-group/silverstripe-statefulunsavedlist](https://github.com/webbuilders-group/silverstripe-statefulunsavedlist) which only works with many_many relationships that have the right side of the relationship existing. But won't work where the right side of the relationship is not existing (you have to click the add new) or you try to edit the right side object. It also doesn't work with has_many relationships.

**Comment by petrklus** [comment]
Thank you very much for your reply! What is puzzling me that I should not be hitting the error, I am not using (to my knowledge) any unsaved objects!

My use case:

Itinerary object has_one DayToDayExtraDocuments
DayToDayExtraDocuments has_many Itinerary

I provide front-end interface to edit itineraries, and I would also like to provide editor for the attached additional documents. 

Am I doing anything wrong in terms of its usage? All of the Itinerary objects are stored in the database prior for the editor to be loaded, only new objects are ones I actually want to create using the FrontEndGridField

**Comment by UndefinedOffset** [comment]
Hmm ya it would seem like for some reason the Itinerary object that the GridField is getting for what ever reason is not the one that it should be outside of the GridField. I wonder can you post some of the code that you are using to display the FrontEndGridField. It maybe that for some reason the Itinerary object is getting reset. If you [look here](https://github.com/silverstripe/silverstripe-framework/blob/3.1/model/DataObject.php#L1479-L1485) when a component is retrieved from a DataObject (like your Itinerary object) if it does not have an ID it generates an UnsavedRelationList. So somewhere along the line between you're controller that is displaying the root form to the point where the GridField is displayed the Itinerary object looses it's ID. I wonder are you using Form::loadDataFrom() or simply populating each field manually?

**Comment by petrklus** [comment]
Sure!

To start with, the template that renders the form in the front-end (and that works fine for upload fields, normal fields, etc.):

```
$TravelPackTabForm($BookingRequest.Itinerary.ID)
```

Then, the code of the form is following (method of the controller):

```
    public function TravelPackTabForm($id=null) {        
        if (is_string($id) || is_int($id)) {
            // restore if ID passed
            $itinerary = Itinerary::get()->byID($id);                    
            $fields = $itinerary->getTravelPackFields();
        } else {
            $fields = singleton('Itinerary')->getTravelPackFields();            
        }
                
        $actions = new FieldList(    
            new FormAction('storeItineraryForm', 'Store information')
        );    
                        
        $validator = new RequiredFields();

        if (is_string($id) || is_int($id)) {
            $fields->push(new HiddenField("ItineraryID", "ItineraryID", $id));
        } else if (is_null($id)) {
            $fields->push(new HiddenField("ItineraryID", "ItineraryID", 0));
        }

        $fields->push(new HiddenField("RedirectHash","RedirectHash", "request_travel_pack"));

        $form = new Form($this, 'TravelPackTabForm', $fields, $actions, $validator); 

        if (is_string($id) || is_int($id)) {
            // restore if ID passed
            $itinerary = Itinerary::get()->byID($id);                    
            $form->loadDataFrom($itinerary);
        }
        
        return $form;
    } 
```

And lastly, the method if the Itinerary that returns the field we need:

```
    
    public function getTravelPackFields() {
        $fields = new FieldList();

        $fields->push(
            new CheckboxField(
                $name = "UseGlobalTravelPack",
                $title = "Use global travel pack" 
            )                        
        );  

        $gridFieldConfig = FrontEndGridFieldConfig_RelationEditor::create();        
	    $gDayVis = new FrontEndGridField("DayToDayExtraDocuments", "Additional documents", $this->DayToDayExtraDocuments(), $gridFieldConfig);			
	    $fields->push($gDayVis);     

        $separate_tab = array("PreTravelInfoFile", 'PackingListFile','FAQsFile', 'EcoPackFile' );
        foreach ($separate_tab as $field_name) {
            $fields->push(
                new UploadField(
                    $name = $field_name,
                    $title = $field_name
                )                        
            );     
        }
        
        // more file HTML edit boxes
        $separate_tab = array("PreTravelInfo", 'PackingList','FAQs', 'EcoPack' );
        foreach ($separate_tab as $field_name) {
            $fields->push(
                new HtmlEditorField(
                    $name = $field_name,
                    $title = $field_name
                )                        
            );     
        }
        
        return $fields;
    }
```

And lastly, method to save the data:

```
    public function storeItineraryForm($data, $form) {
        if ($data["ItineraryID"] == 0) {
            $itinerary = false;
        } else {
            $itinerary = Itinerary::get()->byID($data["ItineraryID"]);
        }
        
        if (!$itinerary) {
            throw new Exception("Invalid or missing itinerary ID!");
        }
        
        // store the form data
        $form->saveInto($itinerary);

        // save to database
        $itinerary->write();

        if ($data["RedirectHash"]) {
            $hash = $data["RedirectHash"];
        } else {
            $hash = "request_itinerary";
        }
        

        // go back to info file
        return $this->redirect("/frontendeditor/view_request/".$itinerary->BookingRequest()->ID."#".$hash);
    }  
```

**Comment by UndefinedOffset** [comment]
I wouldn't doubt it's something to do with how you are getting the id of the Itinerary object into the form. Try a simple test when you are viewing a DayToDayExtraDocument put a print and exit into the TravelPackTabForm() method in the first if and else condition see which part you are hitting. I'm thinking it's probably going to the else.

**Comment by petrklus** [comment]
Ok, will try that - but in the meantime, my insight from previous
experiments is following:

- initially, when the page is loaded, the ID is loaded from the parameter
and itinerary object is loaded
- after the form is submitted, the itinerary singleton is loaded (this one
has hidden ItineraryID field with the actual itinerary ID) and form object
created
- in the storeItineraryForm, itinerary is restored based on the ItineraryID
data field, then the form is saved into it

If my understanding is correct, then I should be able to extract the the
ItinearyID and load the itinerary object during the form load, rather than
using empty singleton to create the form object.

However, to pose a broader question re. the above - isn't this the way SS
usually works - ie. the form is often created with an empty class, only to
be saved into the fully loaded object?

**Comment by UndefinedOffset** [comment]
Hmm yes and no depends on the implementation you are doing, for example a contact form likely doesn't load anything from the database. But say when you are editing a page it's loaded from the database before the form is sent to the browser. In the case of editing an object in a GridField in the pages section for example the current page's id is stored in the session [see here](https://github.com/silverstripe/silverstripe-framework/blob/3.1/admin/code/LeftAndMain.php#L1451-L1461) which is why you can refresh the page and still edit the object inside of the GridField. Where FrontEndGridField is using another url to edit or create the object you need some way of maintaining the reference to the correct parent object much like the cms page's section does.

The big trick with GridField's is that your template is not called on first when looking at a GridField item edit form, the quick fix maybe to simply store the ID of the Itinerary object into the session and use that to reload the correct Itinerary object from the database. Or to pass it through the url (which is what I would recommend trying to get working). Because of how you are re-loading the object the GridField is unaware of the correct parent object since when the GridFieldItemEditForm is loaded it's using the singleton (which hasn't been written). Which is causing your UnsavedRelationList issue. Pretty sure that's what going on here, try the print & exit thing I was suggesting see what that surfaces.

**Comment by petrklus** [comment]
Ok, I got it to working.. though I am not very happy with the result:

```
        if (is_object($id) && is_a($id, "SS_HTTPRequest")) {
            $parts = explode("/", $id->getHeader('Referer'));
            $id_try = intval($parts[5]);
            if ($parts[3] == "frontendeditor") {
                if ($itinerary = BookingRequest::get()->byID($id_try)->Itinerary()) {
                    $fields = $itinerary->getTravelPackFields();                
                } else {
                    Debug::show("Problem!");
                    die();
                }
            } else {                
                $url = $id->getURL();
                $url_parts = explode("/", $url);
                if ($url_parts[3] == "DayToDayExtraDocuments") {
                    if (array_key_exists("ParentItineraryID", $id->postVars())) {
                        $postVars = $id->postVars();
                        $itinerary = Itinerary::get()->byID($postVars["ParentItineraryID"]);
                        $fields = $itinerary->getTravelPackFields();  
                    } else {
                        $obj = DayToDayExtraDocument::get()->byID($url_parts[5]);
                        if ($obj) {
                            $itinerary = $obj->ParentItinerary();
                            $fields = $itinerary->getTravelPackFields();  
                        } else {
                            Debug::show($id);
                            die();    
                        }
                    }
                                  
                } else {
                    Debug::show($url);
                    Debug::show($url_parts);
                    die();
                }
            }
        }
```

I've effectively had to anticipate what happens in the internal logic at any point and then get the state. I cannot really use session, as one can imagine editing multiple pages at the same time, and I do not want to restrict it in any way. I effectively needed to detect various stages of submission / form loading and substitute in the correct ID, either from referrer/url or from the actual object once it's loaded.

**Comment by UndefinedOffset** [comment]
You maybe able to append the ID of the source record to the FormAction, maybe as a get variable. If you do it in the normal silverstripe url way it'd require shuffling things around so the fields are handled correctly. I'd probably do that as a solution though I'd need to play with it.

Could try something like this, though I haven't tested it and I did this just out of guessing more or less
```php
public function TravelPackTabForm($id=null) {        
    if (is_string($id) || is_int($id)) {
        // restore if ID passed
        $itinerary = Itinerary::get()->byID($id);                    
        $fields = $itinerary->getTravelPackFields();
    } else if($this->request->getVar('id') && $this->request->getVar('id')>0) {
        // restore if ID passed
        $itinerary = Itinerary::get()->byID(intval($this->request->getVar('id')));                    
        $fields = $itinerary->getTravelPackFields();
    } else {
        $fields = singleton('Itinerary')->getTravelPackFields();            
    }

    $actions = new FieldList(    
        new FormAction('storeItineraryForm', 'Store information')
    );    

    $validator = new RequiredFields();

    if (is_string($id) || is_int($id)) {
        $fields->push(new HiddenField("ItineraryID", "ItineraryID", $id));
    } else if (is_null($id)) {
        $fields->push(new HiddenField("ItineraryID", "ItineraryID", 0));
    }

    $fields->push(new HiddenField("RedirectHash","RedirectHash", "request_travel_pack"));

    $form = new Form($this, 'TravelPackTabForm', $fields, $actions, $validator);
    $form->setFormAction(Controller::join_links($form->FormAction(), '?id='.$itinerary->ID));

    if (is_string($id) || is_int($id)) {
        // restore if ID passed
        $itinerary = Itinerary::get()->byID($id);                    
        $form->loadDataFrom($itinerary);
    }
    
    return $form;
}
```
