### ISSUE TITLE
Build new Tag from current Master

### ISSUE THREAD

**Issue by andrelohmann** [webbuilders-group/silverstripe-frontendgridfield#9]
Hi, Your Module really is awesome, but you missed to add your last changes to a new Tag. The last Tag (1.1) is about a year ago and espaecially the changes in your composer file (to install the module to "frontendgridfield" instead of "silverstripe-frontendgridfield" Folder) is still missing when trying to install the module by composer.

**Comment by UndefinedOffset** [comment]
New tag created as 0.2.0
